### ISSUE TITLE
Stanadlone dev environment for contributors

### ISSUE THREAD

**Issue by kazazes** [kazazes/trumpsaid-wtf#40]
Create a standalone dev environment decoupled from GCE and Auth0.

- [ ] Bring up prisma, redis, mysql, ELK and TS in docker compose
- [ ] #37 Seed prisma with mock data
- [ ] #21 - Decouple from GCE for processing. Run in containers locally.
- [ ] Find storage alternative
- [ ] #34 Determine solution to auth0 secrets problem
